### ISSUE TITLE
Fix emoji 直接帶入誤差

### ISSUE THREAD

**Issue by Peter-Liao-github** [benben6515/notion-tool#12]
<img width="786" alt="截圖 2023-06-19 17 53 32" src="https://github.com/benben6515/notion-tool/assets/30005366/bd2206d0-7b1e-458d-8b88-e0f7ac67c403">

看要不要做幾個常用的放在 radio button 裡，自行輸入的附近帶 tooltip 警語

**Comment by benben6515** [comment]
已更新成自動當前字元的長度～
