### ISSUE TITLE
Notion formula string 產出

### ISSUE THREAD

**Issue by Peter-Liao-github** [benben6515/notion-tool#2]
- 雷蒙文
https://raymondhouch.com/lifehacker/digital-workflow/notion-progress-bar/
- 國外 Notioner 文 ( 下圖來源 )
https://www.notion.so/Progress-Bar-b908b8a1e4804ca5a6ababb313b216bc

<img width="1540" alt="截圖 2023-06-16 14 37 38" src="https://github.com/benben6515/notion-tool/assets/30005366/4a4bee11-9cf2-483c-8e83-37fa2e44a6ba">

**Simple**
```
if(prop("Completed") / prop("Goal") >= 1, "✅", if(empty(prop("Completed")) and not empty(prop("Goal")), "0%", replaceAll(slice("xxxxxxxxxx", 0, floor(prop("Completed") / prop("Goal") * 10)), "x", "⭐️") + " " + format(floor(prop("Completed") / prop("Goal") * 100)) + "%"))
```

**Full**
```
if(prop("Completed") / prop("Goal") >= 1, "✅", replaceAll(slice("xxxxxxxxxx", 0, floor(prop("Completed") / prop("Goal") * 10)), "x", "🌳") + replaceAll(slice("xxxxxxxxxx", 0, ceil(10 - prop("Completed") / prop("Goal") * 10)), "x", "🌱") + " " + format(floor(prop("Completed") / prop("Goal") * 100)) + "%")
```

**Comment by benben6515** [comment]
這邊目前完成 full bar 的部分

- [ ] simple bar
- [x] full bar

---

發現還有其他細節，再開另一張 ticket 好了 😂
