### ISSUE TITLE
圖示替換快捷按鈕 (radio)

### ISSUE THREAD

**Issue by Peter-Liao-github** [benben6515/notion-tool#6]
<img width="496" alt="截圖 2023-06-17 16 58 34" src="https://github.com/benben6515/notion-tool/assets/30005366/237a0eeb-0647-4ee7-bd12-b03a7df87a3d">

**Comment by benben6515** [comment]
這邊我有寫一個 copy 的 hook ，有需要可以直接用

![Image](https://github.com/benben6515/notion-tool/assets/61361198/6ac2223f-6c7b-4317-8214-93de7eef4baa)


覺得我們可以全部放一排在下面，然後把他做成按鈕，讓使用者點擊一下就 copy 之類的
P 大覺得呢 👀

**Comment by Peter-Liao-github** [comment]
對耶，點擊一下就 copy 也很方便
我想一下 UI，弄好再貼 wireframe 過來，看要哪一個

**Comment by Peter-Liao-github** [comment]
option A copy button
![Image](https://github.com/benben6515/notion-tool/assets/30005366/2b235a33-6aa3-4aa3-8881-8ff17f6c4a76)

option B choose button
![Image](https://github.com/benben6515/notion-tool/assets/30005366/b1c7f44f-d629-43eb-9f44-618d6554f439)

option C
BenBen 大的其他想法

**Comment by benben6515** [comment]
我想選 B 欸，比較接近掛掉的那個網站 XD

**Comment by Peter-Liao-github** [comment]
- [x] toggle list panel
- [x] buttons group
- [ ] to be component
